LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := SDL2_FC

LOCAL_CFLAGS := -DFC_USE_SDL_GPU

LOCAL_C_INCLUDES := $(LOCAL_PATH)

LOCAL_SRC_FILES := SDL_FontCache.c

LOCAL_SHARED_LIBRARIES := SDL2 SDL2_gpu

LOCAL_STATIC_LIBRARIES := SDL2_ttf

LOCAL_EXPORT_C_INCLUDES += $(LOCAL_C_INCLUDES)

LOCAL_CFLAGS += -O3


include $(BUILD_SHARED_LIBRARY)
